apiVersion: v1
kind: Service
metadata:
  name: npm-registry
  namespace: registry
  labels:
    app: npm-registry
    service: npm-registry
spec:
  type: ClusterIP
  selector:
    app: npm-registry
  ports:
    - name: http
      port: 4873
      targetPort: http
      protocol: TCP
  sessionAffinity: None
